main:
  build: ./main
  ports:
    - "8000:5000"
  volumes:
    - ./main:/usr/src
  links:
    - mongodb

mongodb:
  image: mongo

jobs:
  build: ./jobs
  volumes:
    - ./jobs:/app
  links:
    - main

